### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by lcmen**
There was a typo in condition that checks if scope id has been set.

### CODE REVIEW

**Comment by GuillaumeCisco** [comment]
Hey @lowski , pleaser refer to my pull request for other fixes : https://github.com/ds62987/angular-jwplayer/pull/3

No news from @ds62987 for 15 days.
This PR should be merged as soon as possible.

**Comment by lcmen** [comment]
Hi @GuillaumeCisco, I'm not sure how referring pull requests is working on Github. Should I edit this PR?

**Comment by GuillaumeCisco** [comment]
Nope, no need.
Indeed you've fixed a code error in your PR. But if you go further, you'll see there is a lot of misunderstanding of angular concepts in today's code.

I fixed them in PR #3 for having things the right way!
Have a look at it. I've also updated the README file for better understanding purposes.

Thanks for your interest @lowski

**Comment by lcmen** [comment]
@GuillaumeCisco I didn't know that, thanks! I have fixed undefined because the second condition was never met in my app. Unfortunately it looks like all our efforts are unnoticeable - all PRs are still open without any comment from @ds62987 .

**Pull request merged**
