### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by GuillaumeCisco**
Fix undefined bug
Fix wrong id attribute handling
Fix wrong usage of template
Simplify and Refacto
Update README and index.html

### CODE REVIEW

**Comment by GuillaumeCisco** [comment]
@ds62987 You should consider this code and quickly merge it.
Fix a lot of angular misunderstanding and simplify code.

**Comment by FunctionallyLiterate** [comment]
Sorry it took so long to do the merge.  I didn't realize people were really using this project.  It was really just an experiment of mine while learning grunt and angular.

Thanks for the contribution!

**Comment by GuillaumeCisco** [comment]
Hello @ds62987,
Thanks for taking the time to read our modifications.
But you've just merged #4 and closed #3
Although #4 is just a quick fix. #3 is a complete refactoring for following angular philosophy.
As I described it in #4 comments. The `id` reference will never work as it is a reserved attribute.
That's why I replaced it with `playerId`.
Moreover, I don't think this quick merge also modified the minified version of the file in the dist directory.
Thank you for your time.
Please have a deep look in this code refactoring.

**Comment by FunctionallyLiterate** [comment]
Sorry about that.  Would you like to be a collaborator on the project so you can just directly merge changes without me?  I probably won't really maintain this project going forward, but I'd be happy to make you a collaborator.  I could also just update the readme to link to your fork if you want.

**Comment by GuillaumeCisco** [comment]
Yes, it will be great.
Thank you for your interest.

**Pull request closed without merging**
